package net.engineerAnsh.BankApplication.Security.Jwt;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import javax.crypto.SecretKey;
import java.util.Date;
import java.util.List;

@Component
public class JwtUtils {

    // JWT secret must be Base64 and at least 32 bytes long...
    @Value("${jwt.secret.key}") // @Value → reads values from config...
    private String secretKey;// it should be greater than 32 bytes...

    @Value("${jwt.token.time}") // @Value → reads values from config...
    private long expiration;

    // This converts your secret string into a special format (SecretKey)
    // that the JWT library can use for encryption and signature verification...
    private SecretKey getSigningKey() {// Key → used to sign & verify token...
        byte[] secretKeyBytes = Decoders.BASE64.decode(secretKey);
        return Keys.hmacShaKeyFor(secretKeyBytes); // Keys.hmacShaKeyFor → creates secure signing key...
    }

    // It verifies a JWT token and extracts all its claims (data inside the token), Claims = information stored inside JWT...
    // This JSON is returned as a Claims object...
    // {"sub": "raj@gmail.com", "iat": 1710000000, "exp": 1710086400, "roles": ["ROLE_USER"]}
    // In simple words: “Use my secret key to verify this JWT → make sure it’s valid and not expired → give me the data inside it.”
    private Claims extractAllClaims(String token) {
        return Jwts.parser()// Creates a JWT parser. Think of it as: “I want to read and verify a JWT token.”
                .verifyWith(getSigningKey())// Tells the parser which cryptographic key to use to verify the token’s signature, Why this matters: JWTs are signed using a secret/private key...
                .build()// Finalizes the parser configuration and creates an immutable parser instance...
                .parseSignedClaims(token)// This is where the actual verification + parsing happens, It checks automatically: JWT format is valid, Signature matches the signing key, Token is not expired (exp), Token is not malformed
                .getPayload();// Extracts the payload (aka claims) from the verified token, Payload = data inside JWT...
    }

    // Extract Username (Email) from Token...
    public String extractEmail(String token) {
        return extractAllClaims(token).getSubject();
    }

    // Extract Roles from Token...
    public List<?> extractRoles(String token) {
        return extractAllClaims(token).get("roles", List.class);
    }

    // This method will run 'extractAllClaims(String xyz)' , and if:
    // the method don't throw any error it means the token is valid, else token is not valid...
    public boolean isTokenValid(String token) {
        try {
            extractAllClaims(token);
            return true;
        } catch (JwtException | IllegalArgumentException e) {
            return false;
        }
    }

    // It creates a JWT token that contains the user’s identity and roles, signs it securely,& returns it as a string...
    // This is called after successful login...
    public String generateToken(String email, List<String> roles) {
        return Jwts.builder()// Starts building a new JWT, Think of it like creating an empty token...
                .subject(email) // Sets the owner of the token, This is stored as sub inside JWT (meaning: “This token belongs to this email”)...
                .claim("roles", roles)// Adds extra information inside the token, Here you store user roles...
                .header().empty().add("type", "jwt")// Modifies the header part of JWT...
                .and()
                .issuedAt(new Date(System.currentTimeMillis())) // token creation time...
                .expiration(new Date(System.currentTimeMillis() + expiration)) // token expiry time...
                .signWith(getSigningKey()) // uses your secret key to secure(sign) the token...
                .compact();//Converts everything into one long string, This is the JWT a client receives...
    }

}
